[versions]
kotlin-gradle-plugin = "2.0.0"
kotlin = "2.0"
ktor = "3.0.0"
kotlinx-serialization = "1.7.3"
kotlinx-coroutine = "1.9.0"
kotest = "5.9.1"
logback = "1.4.12"
exposed = "0.56.0"
postgres = "42.7.4"

[libraries]
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
ktor-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor"}
ktor-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor"}
ktor-websockets = { module = "io.ktor:ktor-server-websockets-jvm", version.ref = "ktor" }
ktor-cors = { module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-statuspage = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref  = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-json =  { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor"}
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor"}
kotlinx-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutine"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization"}
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }


[bundles]
ktor-server = [
    "ktor-core",
    "ktor-netty",
    "ktor-cors",
    "ktor-serialization-jackson",
    "ktor-serialization-json",
    "ktor-websockets",
    "ktor-contentnegotiation",
    "ktor-statuspage",
    "ktor-server-swagger",
]

ktor-client = [
    "ktor-client-core",
    "ktor-client-cio",
]

test-kotest = [
    "kotest-assertions",
    "kotest-assertions-core",
    "kotest-framework-datatest",
    "kotest-framework-engine",
    "kotest-runner",
]

exposed = [
    "exposed-core",
    "exposed-jdbc",
    "exposed-dao",
    "exposed-java-time",
]

[plugins]
ktor-plugin = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.0.20" }
